============================= test session starts ==============================
platform darwin -- Python 3.10.12, pytest-8.0.0, pluggy-1.3.0 -- /usr/local/opt/python@3.10/bin/python3.10
cachedir: .pytest_cache
Test order randomisation NOT enabled. Enable with --random-order or --random-order-bucket=<bucket_type>
rootdir: /Users/sadekmahmood/Projects/ECSE429
plugins: bdd-7.1.1, random-order-1.1.1
collecting ... collected 179 items / 1 error

==================================== ERRORS ====================================
____________ ERROR collecting part_a/categories/test_categories.py _____________
part_a/categories/test_categories.py:1: in <module>
    import requests
/usr/local/lib/python3.10/site-packages/requests/__init__.py:45: in <module>
    from .exceptions import RequestsDependencyWarning
/usr/local/lib/python3.10/site-packages/requests/exceptions.py:9: in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
/usr/local/lib/python3.10/site-packages/requests/compat.py:11: in <module>
    import chardet
/usr/local/lib/python3.10/site-packages/chardet/__init__.py:24: in <module>
    from .universaldetector import UniversalDetector
/usr/local/lib/python3.10/site-packages/chardet/universaldetector.py:49: in <module>
    from .macromanprober import MacRomanProber
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:879: in exec_module
    ???
<frozen importlib._bootstrap_external>:975: in get_code
    ???
<frozen importlib._bootstrap_external>:1074: in get_data
    ???
E   KeyboardInterrupt
=============================== warnings summary ===============================
part_a/test_app.py:6
  /Users/sadekmahmood/Projects/ECSE429/part_a/test_app.py:6: PytestUnknownMarkWarning: Unknown pytest.mark.run_first - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.run_first

part_a/test_app.py:12
  /Users/sadekmahmood/Projects/ECSE429/part_a/test_app.py:12: PytestUnknownMarkWarning: Unknown pytest.mark.run_last - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.run_last

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR part_a/categories/test_categories.py - KeyboardInterrupt
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 1.08s =========================
